# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true
notifications:
  email: false
